version: "3"

services:
    db:
        image: mongo
        ports:
            - "27017:27017"
        container_name: db
        restart: always
        volumes: 
            - ./data:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        networks:
            - rede

    etl:
        build:
            context: ./src
            dockerfile: Dockerfile
        container_name: python3.8
        depends_on: 
            - db
        environment: 
            - MONGOADD=mongodb://admin:admin@db:27017/ 
            - DBNAME=camara 
            - COLLNAME=discursos 
            - START_LEGIS=52
        networks:
            - rede

networks:
    rede:
        driver: bridge
        