version: "3"

services:
    db:
        image: mongo
        ports:
            - "27017:27017"
        container_name: db
        restart: unless-stopped
        volumes: 
            - dbdata:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME : "admin"
            MONGO_INITDB_ROOT_PASSWORD : "admin"
        networks:
            - rede

    etl:
        build:
            context: ./src
            dockerfile: Dockerfile
        container_name: etl_python3.8
        depends_on: 
            - db
        environment: 
            MONGOADD : "mongodb://admin:admin@db:27017/"
            DBNAME : "camara"
            COLLNAME : "discursos" 
            START_LEGIS : 52
        networks:
            - rede

networks:
    rede:
        driver: bridge

volumes:
    dbdata:
        